In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
from tensorflow import keras

In [9]:
df=pd.read_csv('/media/aj/F/Rock Vs Mine/sonar.all-data.csv',header=None)

In [10]:
df

0       1       2       3       4       5       6       7       8   \
0    0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109   
1    0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
2    0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   
3    0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598   
4    0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564   
..      ...     ...     ...     ...     ...     ...     ...     ...     ...   
203  0.0187  0.0346  0.0168  0.0177  0.0393  0.1630  0.2028  0.1694  0.2328   
204  0.0323  0.0101  0.0298  0.0564  0.0760  0.0958  0.0990  0.1018  0.1030   
205  0.0522  0.0437  0.0180  0.0292  0.0351  0.1171  0.1257  0.1178  0.1258   
206  0.0303  0.0353  0.0490  0.0608  0.0167  0.1354  0.1465  0.1123  0.1945   
207  0.0260  0.0363  0.0136  0.0272  0.0214  0.0338  0.0655  0.1400  0.1843   

         9   ...      51      52      53      54      55      56      57  \
0    0.2111  ...  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180  0.0084   
1    0.2872  ...  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140  0.0049   
2    0.6194  ...  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316  0.0164   
3    0.1264  ...  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050  0.0044   
4    0.4459  ...  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072  0.0048   
..      ...  ...     ...     ...     ...     ...     ...     ...     ...   
203  0.2684  ...  0.0116  0.0098  0.0199  0.0033  0.0101  0.0065  0.0115   
204  0.2154  ...  0.0061  0.0093  0.0135  0.0063  0.0063  0.0034  0.0032   
205  0.2529  ...  0.0160  0.0029  0.0051  0.0062  0.0089  0.0140  0.0138   
206  0.2354  ...  0.0086  0.0046  0.0126  0.0036  0.0035  0.0034  0.0079   
207  0.2354  ...  0.0146  0.0129  0.0047  0.0039  0.0061  0.0040  0.0036   

         58      59  60  
0    0.0090  0.0032   R  
1    0.0052  0.0044   R  
2    0.0095  0.0078   R  
3    0.0040  0.0117   R  
4    0.0107  0.0094   R  
..      ...     ...  ..  
203  0.0193  0.0157   M  
204  0.0062  0.0067   M  
205  0.0077  0.0031   M  
206  0.0036  0.0048   M  
207  0.0061  0.0115   M  

[208 rows x 61 columns]

In [11]:
df.shape 

(208, 61)

In [16]:
# checking missing Value

df.isnull().sum()

0     0
1     0
2     0
3     0
4     0
     ..
56    0
57    0
58    0
59    0
60    0
Length: 61, dtype: int64

In [17]:
df[60].value_counts()

M    111
R     97
Name: 60, dtype: int64

In [18]:
X=df.drop(60,axis=1)
y=df[60]

In [19]:
X

0       1       2       3       4       5       6       7       8   \
0    0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109   
1    0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
2    0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   
3    0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598   
4    0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564   
..      ...     ...     ...     ...     ...     ...     ...     ...     ...   
203  0.0187  0.0346  0.0168  0.0177  0.0393  0.1630  0.2028  0.1694  0.2328   
204  0.0323  0.0101  0.0298  0.0564  0.0760  0.0958  0.0990  0.1018  0.1030   
205  0.0522  0.0437  0.0180  0.0292  0.0351  0.1171  0.1257  0.1178  0.1258   
206  0.0303  0.0353  0.0490  0.0608  0.0167  0.1354  0.1465  0.1123  0.1945   
207  0.0260  0.0363  0.0136  0.0272  0.0214  0.0338  0.0655  0.1400  0.1843   

         9   ...      50      51      52      53      54      55      56  \
0    0.2111  ...  0.0232  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180   
1    0.2872  ...  0.0125  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140   
2    0.6194  ...  0.0033  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316   
3    0.1264  ...  0.0241  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050   
4    0.4459  ...  0.0156  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072   
..      ...  ...     ...     ...     ...     ...     ...     ...     ...   
203  0.2684  ...  0.0203  0.0116  0.0098  0.0199  0.0033  0.0101  0.0065   
204  0.2154  ...  0.0051  0.0061  0.0093  0.0135  0.0063  0.0063  0.0034   
205  0.2529  ...  0.0155  0.0160  0.0029  0.0051  0.0062  0.0089  0.0140   
206  0.2354  ...  0.0042  0.0086  0.0046  0.0126  0.0036  0.0035  0.0034   
207  0.2354  ...  0.0181  0.0146  0.0129  0.0047  0.0039  0.0061  0.0040   

         57      58      59  
0    0.0084  0.0090  0.0032  
1    0.0049  0.0052  0.0044  
2    0.0164  0.0095  0.0078  
3    0.0044  0.0040  0.0117  
4    0.0048  0.0107  0.0094  
..      ...     ...     ...  
203  0.0115  0.0193  0.0157  
204  0.0032  0.0062  0.0067  
205  0.0138  0.0077  0.0031  
206  0.0079  0.0036  0.0048  
207  0.0036  0.0061  0.0115  

[208 rows x 60 columns]

In [21]:
y

0      R
1      R
2      R
3      R
4      R
      ..
203    M
204    M
205    M
206    M
207    M
Name: 60, Length: 208, dtype: object

In [22]:
#creating dummie variable
y=pd.get_dummies(y,drop_first=True)
y.sample(5)

R
162  0
70   1
64   1
149  0
200  0

In [28]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=1,stratify=y)


In [30]:
# Model without drop 
model_without_dropout=keras.Sequential([
    keras.layers.Dense(60,input_dim=60,activation='relu'), # 1st hidden layer
    keras.layers.Dense(30,activation='relu'), # 2nd hidden layer
    keras.layers.Dense(15,activation='relu'), # 3rd hidden layer
    keras.layers.Dense(1,activation='sigmoid')# output layer
])

model_without_dropout.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
model_without_dropout.fit(X_train,y_train, epochs=100, batch_size=8)

Epoch 1/100
20/20 [==============================] - 1s 3ms/step - loss: 0.6775 - accuracy: 0.6026
Epoch 2/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6469 - accuracy: 0.6859
Epoch 3/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6174 - accuracy: 0.6923
Epoch 4/100
20/20 [==============================] - 0s 2ms/step - loss: 0.5888 - accuracy: 0.7115
Epoch 5/100
20/20 [==============================] - 0s 2ms/step - loss: 0.5401 - accuracy: 0.7436
Epoch 6/100
20/20 [==============================] - 0s 3ms/step - loss: 0.5180 - accuracy: 0.8013
Epoch 7/100
20/20 [==============================] - 0s 3ms/step - loss: 0.4765 - accuracy: 0.7949
Epoch 8/100
20/20 [==============================] - 0s 2ms/step - loss: 0.4483 - accuracy: 0.7756
Epoch 9/100
20/20 [==============================] - 0s 3ms/step - loss: 0.4702 - accuracy: 0.7821
Epoch 10/100
20/20 [==============================] - 0s 3ms/step - loss: 0.4054 - accuracy: 0.8205
Epoch 11/

20/20 [==============================] - 0s 2ms/step - loss: 0.0042 - accuracy: 1.0000
Epoch 84/100
20/20 [==============================] - 0s 2ms/step - loss: 0.0040 - accuracy: 1.0000
Epoch 85/100
20/20 [==============================] - 0s 3ms/step - loss: 0.0040 - accuracy: 1.0000
Epoch 86/100
20/20 [==============================] - 0s 3ms/step - loss: 0.0038 - accuracy: 1.0000
Epoch 87/100
20/20 [==============================] - 0s 3ms/step - loss: 0.0044 - accuracy: 1.0000
Epoch 88/100
20/20 [==============================] - 0s 3ms/step - loss: 0.0043 - accuracy: 1.0000
Epoch 89/100
20/20 [==============================] - 0s 3ms/step - loss: 0.0034 - accuracy: 1.0000
Epoch 90/100
20/20 [==============================] - 0s 2ms/step - loss: 0.0035 - accuracy: 1.0000
Epoch 91/100
20/20 [==============================] - 0s 2ms/step - loss: 0.0032 - accuracy: 1.0000
Epoch 92/100
20/20 [==============================] - 0s 2ms/step - loss: 0.0029 - accuracy: 1.0000
Epoch 93/100


In [32]:
model_without_dropout.evaluate(X_test,y_test) # Evaluate on test set

2/2 [==============================] - 0s 3ms/step - loss: 0.7681 - accuracy: 0.8077


[0.7681140303611755, 0.807692289352417]

In [37]:
y_predict=model_without_dropout.predict(X_test).reshape(-1) #prediction

y_predict[:10]

array([2.6350031e-06, 7.0626229e-01, 1.0740459e-03, 3.9428473e-04,
       5.6085020e-01, 9.2813927e-01, 4.7870279e-05, 8.4028125e-01,
       9.9999988e-01, 2.7805567e-04], dtype=float32)

In [46]:
y_predict= np.round(y_predict)
print(y_predict[:10])

[0. 1. 0. 0. 1. 1. 0. 1. 1. 0.]


In [47]:
np.array(y_test[:10]).reshape(1,-1)

array([[0, 0, 1, 1, 0, 0, 0, 1, 1, 0]], dtype=uint8)

In [48]:
np.sum(np.array(y_test[:10]).reshape(1,-1)==y_predict[:10])

5

In [49]:
# printing the metrics
from sklearn.metrics import confusion_matrix, classification_report
print(classification_report(y_test, y_predict))

              precision    recall  f1-score   support

           0       0.91      0.71      0.80        28
           1       0.73      0.92      0.81        24

    accuracy                           0.81        52
   macro avg       0.82      0.82      0.81        52
weighted avg       0.83      0.81      0.81        52



In [57]:
# Model with Dropout
model_with_dropout=keras.Sequential([
    keras.layers.Dense(60,input_dim=60, activation='relu'), # 1st hidden layer
    keras.layers.Dropout(0.5),
    
    keras.layers.Dense(30,activation='relu'), # 2nd
    keras.layers.Dropout(0.5),
    
    keras.layers.Dense(15,activation='relu'), # 3rd
    keras.layers.Dropout(0.5),
    
    keras.layers.Dense(1,activation='sigmoid') # output layer
    

])
model_with_dropout.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
model_with_dropout.fit(X_train,y_train,epochs=100,batch_size=8)


Epoch 1/100
20/20 [==============================] - 1s 2ms/step - loss: 0.6911 - accuracy: 0.5641
Epoch 2/100
20/20 [==============================] - 0s 3ms/step - loss: 0.7343 - accuracy: 0.5000
Epoch 3/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6848 - accuracy: 0.5769
Epoch 4/100
20/20 [==============================] - 0s 3ms/step - loss: 0.6877 - accuracy: 0.5513
Epoch 5/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6702 - accuracy: 0.5385
Epoch 6/100
20/20 [==============================] - 0s 2ms/step - loss: 0.7001 - accuracy: 0.4936
Epoch 7/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6984 - accuracy: 0.5705
Epoch 8/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6546 - accuracy: 0.6154
Epoch 9/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6731 - accuracy: 0.5769
Epoch 10/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6842 - accuracy: 0.5385
Epoch 11/

20/20 [==============================] - 0s 2ms/step - loss: 0.3021 - accuracy: 0.9038
Epoch 84/100
20/20 [==============================] - 0s 2ms/step - loss: 0.3048 - accuracy: 0.8718
Epoch 85/100
20/20 [==============================] - 0s 3ms/step - loss: 0.3051 - accuracy: 0.9038
Epoch 86/100
20/20 [==============================] - 0s 2ms/step - loss: 0.3224 - accuracy: 0.9038
Epoch 87/100
20/20 [==============================] - 0s 2ms/step - loss: 0.2665 - accuracy: 0.8718
Epoch 88/100
20/20 [==============================] - 0s 2ms/step - loss: 0.2791 - accuracy: 0.8782
Epoch 89/100
20/20 [==============================] - 0s 2ms/step - loss: 0.2825 - accuracy: 0.9038
Epoch 90/100
20/20 [==============================] - 0s 4ms/step - loss: 0.2698 - accuracy: 0.8846
Epoch 91/100
20/20 [==============================] - 0s 3ms/step - loss: 0.2516 - accuracy: 0.9167
Epoch 92/100
20/20 [==============================] - 0s 3ms/step - loss: 0.2985 - accuracy: 0.8846
Epoch 93/100


In [58]:
model_with_dropout.evaluate(X_train,y_train)

5/5 [==============================] - 0s 2ms/step - loss: 0.1526 - accuracy: 0.9551


[0.1526007354259491, 0.9551281929016113]

In [59]:
model_with_dropout.evaluate(X_test,y_test)

2/2 [==============================] - 0s 2ms/step - loss: 0.5153 - accuracy: 0.7500


[0.5153485536575317, 0.75]

In [61]:
y_predict=model_with_dropout.predict(X_test).reshape(-1)
y_predict[:10]

array([8.4354477e-05, 5.8689439e-01, 3.7962317e-02, 1.8469375e-01,
       5.2773052e-01, 6.5910476e-01, 2.2622049e-03, 3.3868116e-01,
       9.9870712e-01, 4.4739842e-03], dtype=float32)

In [62]:
y_predict=np.round(y_predict)
y_predict[:10]

array([0., 1., 0., 0., 1., 1., 0., 0., 1., 0.], dtype=float32)

In [69]:
np.array(y_test[:10]).reshape(1,-1)

array([[0, 0, 1, 1, 0, 0, 0, 1, 1, 0]], dtype=uint8)

In [70]:
np.sum(np.array(y_test[:10]).reshape(1,-1)==y_predict[:10])

4

In [65]:
# printing the metrics after dropout
from sklearn.metrics import classification_report
print(classification_report(y_test, y_predict))

              precision    recall  f1-score   support

           0       0.74      0.82      0.78        28
           1       0.76      0.67      0.71        24

    accuracy                           0.75        52
   macro avg       0.75      0.74      0.75        52
weighted avg       0.75      0.75      0.75        52

